platform :android do
  lane :upload_to_production do
    supply(
      json_key_data: ENV["GOOGLE_PLAY_JSON_KEY"],
      package_name: "com.goal.master.league1",

      aab: "build_output/Goal_Master_League_3.aab",

      track: "production",          # ✅ Прод-релиз
      release_status: "draft",  # ✅ Завершённый релиз, сразу публикуется после модерации

      track_promote_release_status: "completed",
      changes_not_sent_for_review: false, # ✅ В проде должно быть false — иначе Google заблокирует
                                           # этот параметр NELЬЗЯ включать в production.

      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true
    )
  end
end
